times = {
    "LOCATIONID": data["LOCATIONID"],
    "OPERATINGROOMID": data["OPERATINGROOMID"],
    "CASEDAY": data["CASEDAY"],
    "BOOKINGTYPEID": data["BOOKINGTYPEID"],
    "DESCRIPTION": data["DESCRIPTION"],
    "PATIENTTYPE": data["PATIENTTYPE"],
    "PROCEDUREID": data["PROCEDUREID"],
    "ORARRIVAL": data["PATIENTARRIVEDDTTM"] - data["PATIENTSENTDTTM"],
    "ORINTAKE": data["PATIENTINDTTM"] - data["PATIENTARRIVEDDTTM"],
    "INDUCTION": data["PATIENTREADYFORDTTM"] - data["PATIENTINDTTM"],
    "PATIENTPREP": data["PREPSTARTDTTM"] - data["PATIENTINDTTM"],
    "PREP": data["INCISIONDTTM"] - data["PREPSTARTDTTM"],
    "EXTUBATION": data["TIMEOUTDTTM"] - data["DRESSINGDTTM"],
    "RECOVERYIN": data["RECOVERYINDTTM"] - data["TIMEOUTDTTM"],
    "RECOVERYOUT": data["RECOVERYOUTDTTM"] - data["RECOVERYINDTTM"],
}
times = pd.DataFrame(times)
